import type { Vegetal } from 'type'

export const vegetals: Vegetal[] = [
  { name_fr: 'Alder', name_lat: 'Alnus' },
  { name_fr: 'Black alder', name_lat: 'Alnus glutinosa' },
  { name_fr: 'Common alder', name_lat: 'Alnus glutinosa' },
  { name_fr: 'False alder', name_lat: 'Ilex verticillata' },
  { name_fr: 'Gray alder', name_lat: 'Alnus incana' },
  { name_fr: 'Speckled alder', name_lat: 'Alnus incana' },
  { name_fr: 'Striped alder', name_lat: 'Ilex verticillata' },
  { name_fr: 'White alder', name_lat: 'Alnus incana' },
  { name_fr: 'Almond', name_lat: 'Prunus amygdalus' },
  { name_fr: 'Tall ambrosia', name_lat: 'Ambrosia trifida' },
  { name_fr: 'Amy root', name_lat: 'Apocynum cannabinum' },
  { name_fr: 'Angel trumpet', name_lat: 'Brugmansia suaveolens' },
  { name_fr: 'Apple', name_lat: 'Malus domestica' },
  { name_fr: 'Apricot', name_lat: 'Prunus armeniaca' },
  { name_fr: 'Arfaj', name_lat: 'Rhanterium epapposum' },
  { name_fr: 'Arizona sycamore', name_lat: 'Platanus wrighitii' },
  { name_fr: 'Arrowwood', name_lat: 'Cornus florida' },
  { name_fr: 'Indian arrowwood', name_lat: 'Cornus florida' },
  { name_fr: 'Ash', name_lat: 'Fraxinus spp.' },
  { name_fr: 'Black ash', name_lat: 'Acer negundo, Fraxinus nigra' },
  { name_fr: 'Blue ash', name_lat: 'Fraxinus pennsylvanica' },
  { name_fr: 'Cane ash', name_lat: 'Fraxinus americana' },
  { name_fr: 'Green ash', name_lat: 'Fraxinus pennsylvanica' },
  { name_fr: 'Maple ash', name_lat: 'Acer negundo' },
  { name_fr: 'Red ash', name_lat: 'Fraxinus pennsylvanica' },
  { name_fr: 'River ash', name_lat: 'Fraxinus pennsylvanica' },
  { name_fr: 'Swamp ash', name_lat: 'Fraxinus pennsylvanica' },
  { name_fr: 'White ash', name_lat: 'Fraxinus americana' },
  { name_fr: 'Water ash', name_lat: 'Acer negundo' },
  { name_fr: 'Azolla', name_lat: 'Azolla' },
  { name_fr: 'Carolina azolla', name_lat: 'Azolla caroliniana' },
  { name_fr: 'Bamboo', name_lat: 'Bambuseae' },
  { name_fr: 'Banana', name_lat: 'Musa paradisica' },
  { name_fr: 'Baobab', name_lat: 'Adansonia' },
  { name_fr: 'Bay', name_lat: 'Umbellularia spp.' },
  { name_fr: 'Bay laurel', name_lat: 'Laurus nobilis (culinary)' },
  { name_fr: 'California bay', name_lat: 'Umbellularia californica' },
  { name_fr: 'Bean', name_lat: 'Fabaceae, specifically Phaseolus spp.' },
  { name_fr: 'Bearberry', name_lat: 'Ilex decidua' },
  { name_fr: 'Bear corn', name_lat: 'Veratrum viride' },
  { name_fr: 'Beech', name_lat: 'Fagus' },
  { name_fr: 'Blue bindweed', name_lat: 'Solanum dulcamara' },
  { name_fr: "Bird's nest", name_lat: 'Daucus carota' },
  { name_fr: "Bird's nest plant", name_lat: 'Daucus carota' },
  { name_fr: 'Birch', name_lat: 'Betula spp.' },
  { name_fr: 'Black birch', name_lat: 'Betula lenta, Betula nigra' },
  { name_fr: 'Bolean birch', name_lat: 'Betula papyrifera' },
  { name_fr: 'Canoe birch', name_lat: 'Betula papyrifera' },
  { name_fr: 'Cherry birch', name_lat: 'Betula lenta' },
  { name_fr: 'European weeping birch', name_lat: 'Betula pendula' },
  { name_fr: 'European white birch', name_lat: 'Betula pendula' },
  { name_fr: 'Gray birch', name_lat: 'Betula alleghaniensis' },
  { name_fr: 'Mahogany birch', name_lat: 'Betula lenta' },
  { name_fr: 'Paper birch', name_lat: 'Betula papyrifera' },
  { name_fr: 'Red birch', name_lat: 'Betula nigra' },
  { name_fr: 'River birch', name_lat: 'Betula nigra, Betula lenta' },
  { name_fr: 'Silver birch', name_lat: 'Betula papyrifera' },
  { name_fr: 'Spice birch', name_lat: 'Betula lenta' },
  { name_fr: 'Sweet birch', name_lat: 'Betula lenta' },
  { name_fr: 'Water birch', name_lat: 'Betula nigra' },
  { name_fr: 'Weeping birch', name_lat: 'Betula pendula' },
  { name_fr: 'White birch', name_lat: 'Betula papyrifera, Betula pendula' },
  { name_fr: 'Yellow birch', name_lat: 'Betula alleghaniensis' },
  { name_fr: 'Bittercress', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Hairy bittercress', name_lat: 'Cardamine hirsuta' },
  { name_fr: 'Bittersweet', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Trailing bittersweet', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Bitterweed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Blackberry', name_lat: 'Rubus pensilvanicus' },
  { name_fr: 'Hispid swamp blackberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Pennsylvania blackberry', name_lat: 'Rubus pensilvanicus' },
  { name_fr: 'Running swamp blackberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Black cap', name_lat: 'Rubus occidentalis' },
  { name_fr: 'Black-eyed Susan', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Blackhaw', name_lat: 'Viburnum prunifolium' },
  { name_fr: 'Blackiehead', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Black-weed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Blueberry', name_lat: 'Vaccinium (Cyanococcus) spp.' },
  { name_fr: 'Blue-of-the-heavens', name_lat: 'Allium caeruleum' },
  { name_fr: 'Bow-wood', name_lat: 'Maclura pomifera' },
  { name_fr: 'Box', name_lat: 'Buxus' },
  { name_fr: 'False box', name_lat: 'Cornus florida' },
  { name_fr: 'Boxelder', name_lat: 'Acer negundo' },
  { name_fr: 'Boxwood', name_lat: 'Buxus, Cornus florida' },
  { name_fr: 'False boxwood', name_lat: 'Cornus florida' },
  { name_fr: 'Sand brier', name_lat: 'Solanum carolinense' },
  { name_fr: 'Brittlebush', name_lat: 'Encelia farinosa' },
  { name_fr: 'Broadleaf', name_lat: 'Plantago major' },
  { name_fr: 'Brown Betty', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Brown-eyed Susan', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Buckeye (California buckeye)', name_lat: 'Aesculus californica' },
  { name_fr: 'buckeye', name_lat: 'Aesculus spp.' },
  { name_fr: 'Buffalo weed', name_lat: 'Ambrosia trifida' },
  { name_fr: 'Butterfly flower', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Butterfly weed', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Cabbage', name_lat: 'Brassica oleracea' },
  { name_fr: 'Clumpfoot cabbage', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Meadow cabbage', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Skunk cabbage', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Swamp cabbage', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'California bay', name_lat: 'Umbellularia californica' },
  { name_fr: 'California buckeye', name_lat: 'Aesculus californica' },
  { name_fr: 'California sycamore', name_lat: 'Platanus racemosa' },
  { name_fr: 'California walnut', name_lat: 'Juglans californica' },
  { name_fr: 'Canada root', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Cancer jalap', name_lat: 'Phytolacca americana' },
  { name_fr: 'Carrot', name_lat: 'Daucus carota' },
  { name_fr: 'Wild carrot', name_lat: 'Daucus carota' },
  { name_fr: 'Carrot weed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Cart track plant', name_lat: 'Plantago major' },
  { name_fr: 'Catalina ironwood', name_lat: 'Lyonothamnus floribundus' },
  { name_fr: 'Cherry', name_lat: 'Prunus spp.' },
  { name_fr: 'Black cherry', name_lat: 'Prunus serotina' },
  { name_fr: 'Cabinet cherry', name_lat: 'Prunus serotina' },
  { name_fr: 'Rum cherry', name_lat: 'Prunus serotina' },
  { name_fr: 'Whiskey cherry', name_lat: 'Prunus serotina' },
  { name_fr: 'Wild cherry', name_lat: 'Prunus avium, Prunus serotina' },
  { name_fr: 'Wild black cherry', name_lat: 'Prunus serotina' },
  { name_fr: 'Chestnut', name_lat: 'Castanea spp.' },
  { name_fr: 'Chigger flower', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Chrysanthemum', name_lat: 'Dendranthema grandiflora' },
  { name_fr: '(True) cinnamon', name_lat: 'Cinnamomum verum' },
  { name_fr: 'Clove', name_lat: 'Syzygium aromaticum' },
  { name_fr: 'Clover', name_lat: 'Trifolium spp.' },
  { name_fr: 'Coakum', name_lat: 'Phytolacca americana' },
  { name_fr: 'Coconut', name_lat: 'Cocos nucifera' },
  { name_fr: 'Coffee plant', name_lat: 'Coffea spp.' },
  { name_fr: 'Colic weed', name_lat: 'Corydalis flavula' },
  { name_fr: 'Collard', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Columbine', name_lat: 'Aquilegia vulgaris' },
  { name_fr: "Hare's colwort", name_lat: 'Sonchus oleraceus' },
  { name_fr: 'Brilliant coneflower', name_lat: 'Rudbeckia fulgida' },
  { name_fr: 'Cutleaf coneflower', name_lat: 'Rudbeckia laciniata' },
  { name_fr: 'Eastern coneflower', name_lat: 'Rudbeckia fulgida' },
  { name_fr: 'Green-headed Coneflower', name_lat: 'Rudbeckia laciniata' },
  { name_fr: 'Orange coneflower', name_lat: 'Rudbeckia fulgida' },
  { name_fr: 'Tall coneflower', name_lat: 'Rudbeckia laciniata' },
  { name_fr: 'Thin-leaved Coneflower', name_lat: 'Rudbeckia triloba' },
  { name_fr: 'Three-leaved Coneflower', name_lat: 'Rudbeckia triloba' },
  { name_fr: 'Blueberry cornel', name_lat: 'Cornus amomum' },
  { name_fr: 'Silky cornel', name_lat: 'Cornus amomum' },
  { name_fr: 'White cornel', name_lat: 'Cornus florida' },
  { name_fr: 'Cornelian tree', name_lat: 'Cornus florida' },
  { name_fr: 'Corydalis', name_lat: 'Corydalis spp.' },
  { name_fr: 'Fern-leaf Corydalis', name_lat: 'Corydalis chelidoniifolia' },
  { name_fr: 'Golden corydalis', name_lat: 'Corydalis aurea' },
  { name_fr: 'Pale corydalis', name_lat: 'Corydalis flavula' },
  { name_fr: 'Pink corydalis', name_lat: 'Corydalis sempervirens' },
  { name_fr: 'Yellow corydalis', name_lat: 'Corydalis lutea' },
  { name_fr: 'Cotton plant', name_lat: 'Gossypium' },
  { name_fr: 'Creeping yellowcress', name_lat: 'Rorippa sylvestris' },
  { name_fr: 'Cress', name_lat: '(several genera)' },
  { name_fr: 'American cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Bank cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Belle Isle cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Bermuda cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Bulbous cress', name_lat: 'Cardamine bulbosa' },
  { name_fr: "Lamb's cress", name_lat: 'Cardamine hirsuta' },
  { name_fr: 'Land cress', name_lat: 'Barbarea verna, Cardamine hirsuta' },
  { name_fr: 'Scurvy cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Spring cress', name_lat: 'Cardamine bulbosa' },
  { name_fr: 'Upland cress', name_lat: 'Barbarea verna' },
  { name_fr: 'Crowfoot', name_lat: 'Cardamine concatenata' },
  { name_fr: "Crow's nest", name_lat: 'Daucus carota' },
  { name_fr: "Crow's toes", name_lat: 'Cardamine concatenata' },
  { name_fr: 'Cucumber', name_lat: 'Cucumis sativus' },
  { name_fr: 'Brown daisy', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Common daisy, daisy', name_lat: 'Bellis perennis' },
  { name_fr: 'Gloriosa daisy', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Poorland daisy', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Yellow daisy', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Yellow ox-eye daisy', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Deadnettle', name_lat: 'Lamium spp.' },
  { name_fr: 'Henbit deadnettle', name_lat: 'Lamium amplexicaule' },
  { name_fr: 'Red deadnettle', name_lat: 'Lamium purpureum' },
  { name_fr: 'Spotted deadnettle', name_lat: 'Lamium maculatum' },
  { name_fr: "Devil's bite", name_lat: 'Veratrum viride' },
  { name_fr: "Devil's darning needle", name_lat: 'Clematis virginiana' },
  { name_fr: "Devil's nose", name_lat: 'Clematis virginiana' },
  { name_fr: "Devil's plague", name_lat: 'Daucus carota' },
  { name_fr: 'Bristly dewberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Swamp dewberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Dindle', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Dogwood', name_lat: 'Cornus spp.' },
  { name_fr: 'American dogwood', name_lat: 'Cornus florida' },
  { name_fr: 'Florida dogwood', name_lat: 'Cornus florida' },
  { name_fr: 'Flowering dogwood', name_lat: 'Cornus florida' },
  { name_fr: 'Japanese flowering dogwood', name_lat: 'Cornus kousa' },
  { name_fr: 'Kousa dogwood', name_lat: 'Cornus kousa' },
  { name_fr: 'Drumstick', name_lat: 'Moringa oleifera' },
  { name_fr: 'Pacific dogwood', name_lat: 'Cornus nuttallii' },
  { name_fr: 'Silky dogwood', name_lat: 'Cornus amomum' },
  { name_fr: 'Swamp dogwood', name_lat: 'Cornus amomum' },
  { name_fr: 'Duck retten', name_lat: 'Veratrum viride' },
  { name_fr: 'Duscle', name_lat: 'Solanum nigrum' },
  { name_fr: 'Durian', name_lat: 'Durio zibethinus' },
  { name_fr: 'Durian kura kura', name_lat: 'Durio testudinarum' },
  { name_fr: 'Durian munjit', name_lat: 'Durio grandiflorus' },
  { name_fr: 'Durian pulu', name_lat: 'Durio kutejensis' },
  { name_fr: 'Red durian', name_lat: 'Durio dulcis' },
  { name_fr: 'Dye-leaves', name_lat: 'Ilex glabra' },
  { name_fr: 'Easter orchid', name_lat: 'Cattleya schroederae' },
  { name_fr: 'Earth gall', name_lat: 'Veratrum viride' },
  { name_fr: 'Elderberry', name_lat: 'Sambucus' },
  { name_fr: 'Elegant lupine', name_lat: 'Lupinus elegans' },
  { name_fr: 'Elephant apple', name_lat: 'Dillenia indica' },
  { name_fr: "English bull's eye", name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Eucalyptus', name_lat: 'Eucalyptus spp.' },
  { name_fr: 'Evergreen huckleberry', name_lat: 'Vaccinium ovatum' },
  { name_fr: 'Extinguisher moss', name_lat: 'Encalypta' },
  { name_fr: 'Eytelia', name_lat: 'Amphipappus' },
  { name_fr: 'Fair-maid-of-France', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Fellenwort', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Felonwood', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Felonwort', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Fennel', name_lat: 'Foeniculum vulgare' },
  { name_fr: 'Boston fern or sword fern', name_lat: 'Nephrolepis exaltata' },
  { name_fr: 'Christmas fern', name_lat: 'Polystichum acrostichoides' },
  { name_fr: 'Coast polypody', name_lat: 'Polypodium scouleri' },
  { name_fr: 'Kimberly queen fern', name_lat: 'Nephrolepis obliterata' },
  { name_fr: 'Korean rock fern', name_lat: 'Polystichum tsus-simense' },
  { name_fr: 'Mosquito fern', name_lat: 'Azolla caroliniana' },
  { name_fr: 'Sword ferns', name_lat: 'Polystichum spp.' },
  { name_fr: 'Water fern', name_lat: 'Azolla caroliniana' },
  { name_fr: 'Western sword fern', name_lat: 'Polystichum munitum' },
  { name_fr: 'Feverbush', name_lat: 'Ilex verticillata' },
  { name_fr: 'Feverfew', name_lat: 'Tanacetum parthenium' },
  { name_fr: 'Fig', name_lat: 'Ficus spp.' },
  { name_fr: 'Common fig', name_lat: 'Ficus carica' },
  { name_fr: 'European flax', name_lat: 'Linum usitatissimum' },
  { name_fr: 'New Zealand flax', name_lat: 'Phormium tenax' },
  { name_fr: 'Fluxroot', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Yellow fumewort', name_lat: 'Corydalis flavula' },
  { name_fr: 'Gallberry', name_lat: 'Ilex glabra' },
  { name_fr: 'Garget', name_lat: 'Phytolacca americana' },
  { name_fr: 'Golden garlic', name_lat: 'Allium moly' },
  { name_fr: 'Wild garlic', name_lat: 'Allium canadense' },
  { name_fr: 'Garlic mustard', name_lat: 'Alliaria petiolata' },
  { name_fr: 'Garlic root', name_lat: 'Alliaria petiolata' },
  { name_fr: "Dame's gilliflower", name_lat: 'Hesperis matronalis' },
  { name_fr: 'Night scented gilliflower', name_lat: 'Hesperis matronalis' },
  { name_fr: "Queen's gilliflower", name_lat: 'Hesperis matronalis' },
  { name_fr: "Rogue's gilliflower", name_lat: 'Hesperis matronalis' },
  { name_fr: 'Winter gilliflower', name_lat: 'Hesperis matronalis' },
  { name_fr: 'Golden buttons', name_lat: 'Tanacetum vulgare' },
  { name_fr: 'Golden chain', name_lat: 'Laburnum' },
  { name_fr: 'Goldenglow', name_lat: 'Rudbeckia laciniata' },
  { name_fr: 'Golden Jerusalem', name_lat: 'Rudbeckia hirta' },
  { name_fr: 'Gordaldo', name_lat: 'Achillea millefolium' },
  { name_fr: 'Goose tongue', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Grapefruit', name_lat: 'Citrus × paradisi' },
  { name_fr: 'Grapevine', name_lat: 'Vitis' },
  { name_fr: 'Groundberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Bristly groundberry', name_lat: 'Rubus hispidus' },
  { name_fr: 'Gutweed', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Haldi', name_lat: 'Curcuma domestica' },
  { name_fr: 'Rock harlequin', name_lat: 'Corydalis sempervirens' },
  { name_fr: 'Yellow harlequin', name_lat: 'Corydalis flavula' },
  { name_fr: 'Hay fever weed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Healing blade', name_lat: 'Plantago major' },
  { name_fr: 'Hedge plant', name_lat: 'Maclura pomifera' },
  { name_fr: 'Hellebore', name_lat: 'Helleborus' },
  { name_fr: 'American white hellebore', name_lat: 'Veratrum viride' },
  { name_fr: 'Big hellebore', name_lat: 'Veratrum viride' },
  { name_fr: 'Black hellebore', name_lat: 'Veratrum nigrum' },
  { name_fr: 'European white hellebore', name_lat: 'Veratrum album' },
  { name_fr: 'False hellebore', name_lat: 'Veratrum album' },
  { name_fr: 'Swamp hellebore', name_lat: 'Veratrum viride' },
  { name_fr: 'White hellebore', name_lat: 'Veratrum album' },
  { name_fr: 'Hemp', name_lat: 'Cannabis sativa' },
  { name_fr: 'Hemp dogbane', name_lat: 'Apocynum cannabinum' },
  { name_fr: 'Hen plant', name_lat: 'Plantago major' },
  { name_fr: 'Herb barbara', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Hogweed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Holly', name_lat: 'Ilex spp.' },
  { name_fr: 'Deciduous holly', name_lat: 'Ilex decidua' },
  { name_fr: 'European holly', name_lat: 'Ilex aquifolium' },
  { name_fr: 'Inkberry holly', name_lat: 'Ilex glabra' },
  { name_fr: 'Meadow holly', name_lat: 'Ilex decidua' },
  { name_fr: 'Swamp holly', name_lat: 'Ilex decidua' },
  { name_fr: 'Winterberry holly', name_lat: 'Ilex verticillata' },
  { name_fr: 'Horse cane', name_lat: 'Ambrosia trifida' },
  { name_fr: "Hound's berry", name_lat: 'Solanum nigrum' },
  { name_fr: 'Huckleberry', name_lat: 'Vaccinium spp.' },
  { name_fr: 'Evergreen huckleberry', name_lat: 'Vaccinium ovatum' },
  { name_fr: 'Trailing red huckleberry', name_lat: 'Vaccinium parvifolium' },
  { name_fr: 'Houseleek', name_lat: 'Sempervivum tectorum' },
  { name_fr: 'Indian hemp', name_lat: 'various genera' },
  { name_fr: 'Indian hemp', name_lat: 'Cannabis indica' },
  { name_fr: 'White Indian hemp', name_lat: 'Asclepias incarnata' },
  { name_fr: 'Indian paintbrush', name_lat: 'Castilleja' },
  { name_fr: 'Indian posy', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Inkberry', name_lat: 'Ilex glabra, Phytolacca americana' },
  { name_fr: 'Ironwood', name_lat: 'Acacia estrophiolata' },
  { name_fr: 'Isle of Man cabbage', name_lat: 'Coincya monensis' },
  { name_fr: 'Itchweed', name_lat: 'Veratrum viride' },
  { name_fr: 'Ivy', name_lat: 'Hedera spp.' },
  { name_fr: 'Jack-by-the-hedge', name_lat: 'Alliaria petiolata' },
  { name_fr: 'Jack-in-the-bush', name_lat: 'Alliaria petiolata' },
  { name_fr: 'Jasmine', name_lat: 'Jasminum officinale' },
  { name_fr: 'Jewel orchid', name_lat: 'Ludisia discolor' },
  { name_fr: 'Jointed rush', name_lat: 'Juncus kraussii' },
  { name_fr: 'Jugflower', name_lat: 'Adenanthos obovatus' },
  { name_fr: 'Juneberry', name_lat: 'Amelanchier canadensis' },
  { name_fr: 'Keek', name_lat: 'Rorippa sylvestris' },
  { name_fr: 'King fern', name_lat: 'Ptisana salicina' },
  { name_fr: 'Kinnikinnik', name_lat: 'Cornus amomum' },
  { name_fr: 'Kittentail', name_lat: 'Veronica bullii' },
  { name_fr: 'Knotweed', name_lat: 'Fallopia japonica' },
  { name_fr: 'Kousa', name_lat: 'Cornus kousa' },
  { name_fr: 'Kudzu', name_lat: 'Pueraria montana' },
  { name_fr: 'Kumarahou', name_lat: 'Pomaderris kumeraho' },
  { name_fr: 'Laceflower', name_lat: 'Daucus carota' },
  { name_fr: 'Lace fern', name_lat: 'Asparagus setaceus' },
  { name_fr: "Lamb's foot", name_lat: 'Plantago major' },
  { name_fr: 'Latanier palm', name_lat: 'Phoenicophorium' },
  { name_fr: 'Laurel magnolia', name_lat: 'Magnolia splendens' },
  { name_fr: 'Lavender', name_lat: 'Lavandula' },
  { name_fr: 'Leek', name_lat: 'Allium' },
  { name_fr: 'Lemon', name_lat: 'Citrus × limon' },
  { name_fr: 'Leopard lily', name_lat: 'Lilium catesbaei' },
  { name_fr: 'Lily of the Nile', name_lat: 'Agapanthus praecox' },
  { name_fr: 'Lettuce', name_lat: 'Lactuca sativa' },
  { name_fr: 'Lily leek', name_lat: 'Allium moly' },
  { name_fr: 'Summer lilac', name_lat: 'Hesperis matronalis' },
  { name_fr: 'Little sunflower', name_lat: 'Helianthella' },
  { name_fr: 'Lone fleabane', name_lat: 'Erigeron cavernensis' },
  { name_fr: 'Love vine', name_lat: 'Clematis virginiana' },
  { name_fr: 'Maize', name_lat: 'Zea mays' },
  { name_fr: 'Mango', name_lat: 'Mangifera indica' },
  { name_fr: 'Maple', name_lat: 'Acer' },
  { name_fr: 'Ash-leaved maple', name_lat: 'Acer negundo' },
  { name_fr: 'Black maple', name_lat: 'Acer nigrum' },
  { name_fr: 'Creek maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Cutleaf maple', name_lat: 'Acer negundo' },
  { name_fr: 'Maple ash', name_lat: 'Acer negundo' },
  { name_fr: 'Moose maple', name_lat: 'Acer pensylvanicum' },
  { name_fr: 'Red river maple', name_lat: 'Acer negundo' },
  { name_fr: 'River maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Silver maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Silverleaf maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Soft maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Striped maple', name_lat: 'Acer pensylvanicum' },
  { name_fr: 'Sugar maple', name_lat: 'Acer saccharum' },
  { name_fr: 'Swamp maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Water maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'White maple', name_lat: 'Acer saccharinum' },
  { name_fr: 'Mesquite', name_lat: 'Prosopis' },
  { name_fr: 'Honey mesquite', name_lat: 'Prosopis glandulosa' },
  { name_fr: 'Screwbean mesquite', name_lat: 'Prosopis pubescens' },
  { name_fr: 'Milfoil', name_lat: 'Achillea millefolium' },
  { name_fr: 'Milkweed', name_lat: 'Asclepias, Sonchus oleraceus' },
  { name_fr: 'Blunt-leaved Milkweed', name_lat: 'Asclepias amplexicaulis' },
  { name_fr: 'Common milkweed', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Horsetail milkweed', name_lat: 'Asclepias verticillata' },
  { name_fr: 'Orange milkweed', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Swamp milkweed', name_lat: 'Asclepias incarnata' },
  { name_fr: 'Rose milkweed', name_lat: 'Asclepias incarnata' },
  { name_fr: 'Whorled milkweed', name_lat: 'Asclepias verticillata' },
  { name_fr: 'Yellow milkweed', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Milky tassel', name_lat: 'Sonchus oleraceus' },
  { name_fr: 'Moosewood', name_lat: 'Acer pensylvanicum' },
  { name_fr: 'Petty morel', name_lat: 'Solanum nigrum' },
  { name_fr: 'Mosquito plant', name_lat: 'Azolla caroliniana' },
  { name_fr: 'Mother-of-the-evening', name_lat: 'Hesperis matronalis' },
  { name_fr: 'Mountain mahogany', name_lat: 'Betula lenta' },
  { name_fr: 'Mulberry', name_lat: 'Morus' },
  { name_fr: 'Red mulberry', name_lat: 'Morus rubra' },
  { name_fr: 'White mulberry', name_lat: 'Morus alba' },
  { name_fr: 'Native fuchsia', name_lat: 'Epacris longiflora' },
  { name_fr: 'Necklace fern', name_lat: 'Asplenium flabellifolium' },
  { name_fr: 'Neem', name_lat: 'Azadirachta indica' },
  { name_fr: 'Nettle', name_lat: 'Urtica dioica' },
  { name_fr: 'Bull nettle', name_lat: 'Solanum carolinense' },
  { name_fr: 'Carolina horse nettle', name_lat: 'Solanum carolinense' },
  { name_fr: 'Horse nettle', name_lat: 'Solanum carolinense' },
  { name_fr: 'Night-blooming cactus', name_lat: 'Hylocereus' },
  { name_fr: 'American nightshade', name_lat: 'Phytolacca americana' },
  { name_fr: 'Bitter nightshade', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Black nightshade', name_lat: 'Solanum nigrum' },
  { name_fr: 'Climbing nightshade', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Deadly nightshade', name_lat: 'Solanum nigrum' },
  { name_fr: 'Garden nightshade', name_lat: 'Solanum nigrum' },
  { name_fr: 'Trailing nightshade', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Trailing violet nightshade', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Woody nightshade', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Nodding wakerobin', name_lat: 'Trillium cernuum' },
  { name_fr: 'Northern moonwort', name_lat: 'Botrychium boreale' },
  { name_fr: 'Nosebleed', name_lat: 'Achillea millefolium' },
  { name_fr: 'Blue oak', name_lat: 'Quercus douglasii' },
  { name_fr: 'Bur oak', name_lat: 'Quercus macrocarpa' },
  { name_fr: 'Champion oak', name_lat: 'Quercus rubra' },
  { name_fr: 'Coast live oak', name_lat: 'Quercus agrifolia' },
  { name_fr: 'Cork oak', name_lat: 'Quercus suber' },
  { name_fr: "Dyer's oak", name_lat: 'Quercus velutina' },
  { name_fr: 'Eastern black oak', name_lat: 'Quercus velutina' },
  { name_fr: 'English oak', name_lat: 'Quercus robur' },
  { name_fr: 'Island oak', name_lat: 'Quercus. tomentella' },
  { name_fr: "Mirbeck's oak", name_lat: 'Quercus canariensis' },
  { name_fr: 'Mossycup white oak', name_lat: 'Quercus macrocarpa' },
  { name_fr: 'Northern red oak', name_lat: 'Quercus rubra' },
  { name_fr: 'Pedunculate oak', name_lat: 'Quercus robur' },
  { name_fr: 'Pin oak', name_lat: 'Quercus palustris' },
  { name_fr: 'Red oak', name_lat: 'Quercus rubra' },
  { name_fr: 'Scarlet oak', name_lat: 'Quercus coccinea' },
  { name_fr: 'Scrub oak', name_lat: 'Quercus macrocarpa' },
  { name_fr: 'Sessile oak', name_lat: 'Quercus petraea' },
  { name_fr: 'Spanish oak', name_lat: 'Quercus coccinea' },
  { name_fr: 'Spotted oak', name_lat: 'Quercus velutina' },
  { name_fr: 'Swamp oak', name_lat: 'Quercus palustris' },
  { name_fr: 'Swamp Spanish oak', name_lat: 'Quercus palustris' },
  { name_fr: 'Swamp white oak', name_lat: 'Quercus bicolor' },
  { name_fr: 'Valley oak', name_lat: 'Quercus lobata' },
  { name_fr: 'White oak', name_lat: 'Quercus alba' },
  { name_fr: 'Yellowbark oak', name_lat: 'Quercus velutina' },
  { name_fr: 'Olive', name_lat: 'Olea europaea' },
  { name_fr: 'Onion', name_lat: 'Allium' },
  { name_fr: 'Common onion', name_lat: 'Allium cepa' },
  { name_fr: 'Giant onion', name_lat: 'Allium giganteum' },
  { name_fr: 'Nodding onion', name_lat: 'Allium cernuum' },
  { name_fr: 'Tree onion', name_lat: 'Allium canadense' },
  { name_fr: 'Wild onion', name_lat: 'Allium canadense' },
  { name_fr: 'Osage orange', name_lat: 'Maclura pomifera' },
  { name_fr: 'sweet orange', name_lat: 'Citrus × sinensis' },
  { name_fr: 'Wild orange', name_lat: 'Maclura pomifera' },
  { name_fr: 'Orange-root', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Osage', name_lat: 'Maclura pomifera' },
  { name_fr: 'Osier', name_lat: 'Salix' },
  { name_fr: 'Red osier', name_lat: 'Cornus amomum' },
  { name_fr: 'Parsley', name_lat: 'Petroselinum crispum' },
  { name_fr: 'Parsnip', name_lat: 'Pastinaca sativa' },
  { name_fr: 'Pea', name_lat: 'Pisum sativum' },
  { name_fr: 'Peach', name_lat: 'Prunus persica' },
  { name_fr: 'Peanut', name_lat: 'Arachis hypogaea' },
  { name_fr: 'Pear', name_lat: 'Pyrus' },
  { name_fr: 'Bastard pellitory', name_lat: 'Achillea ptarmica' },
  { name_fr: 'European pellitory', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Wild pellitory', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Penny hedge', name_lat: 'Alliaria petiolata' },
  { name_fr: 'Pepper root', name_lat: 'Cardamine concatenata' },
  { name_fr: 'Pigeon berry', name_lat: 'Phytolacca americana' },
  { name_fr: 'Pine', name_lat: 'Pinus' },
  { name_fr: 'Pineapple', name_lat: 'Ananas comosus' },
  { name_fr: 'Pistachio', name_lat: 'Pistacia vera' },
  { name_fr: 'Plane (European sycamore)', name_lat: 'Platanus acerifolia' },
  { name_fr: 'Broadleaf plantain', name_lat: 'Plantago major' },
  { name_fr: 'Common plantain', name_lat: 'Plantago major' },
  { name_fr: 'Dooryard plantain', name_lat: 'Plantago major' },
  { name_fr: 'Greater plantain', name_lat: 'Plantago major' },
  { name_fr: 'Roundleaf plantain', name_lat: 'Plantago major' },
  { name_fr: 'Wayside plantain', name_lat: 'Plantago major' },
  { name_fr: 'Pleurisy root', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Pocan bush', name_lat: 'Phytolacca americana' },
  { name_fr: 'Poison ivy', name_lat: 'Toxicodendron radicans' },
  { name_fr: 'Poisonberry', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Poisonflower', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Poke', name_lat: 'Phytolacca americana' },
  { name_fr: 'Indian poke', name_lat: 'Veratrum viride' },
  { name_fr: 'Pokeroot', name_lat: 'Phytolacca americana' },
  { name_fr: 'Pokeweed', name_lat: 'Phytolacca americana' },
  { name_fr: 'Polkweed', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Polecat weed', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Poor Annie', name_lat: 'Veratrum viride' },
  { name_fr: "Poor man's mustard", name_lat: 'Alliaria petiolata' },
  { name_fr: 'Poplar', name_lat: 'Populus' },
  { name_fr: 'Poppy', name_lat: 'Papaveraceae' },
  { name_fr: 'Possumhaw', name_lat: 'Ilex decidua' },
  { name_fr: 'Potato', name_lat: 'Solanum tuberosum' },
  { name_fr: "Queen Anne's lace", name_lat: 'Daucus carota' },
  { name_fr: 'Quercitron', name_lat: 'Quercus velutina' },
  { name_fr: 'Radical weed', name_lat: 'Solanum carolinense' },
  { name_fr: 'Ragweed', name_lat: 'Ambrosia' },
  { name_fr: 'Common ragweed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Giant ragweed', name_lat: 'Ambrosia trifida' },
  { name_fr: 'Great ragweed', name_lat: 'Ambrosia trifida' },
  { name_fr: 'Ragwort', name_lat: 'Senecio' },
  { name_fr: 'Common ragwort', name_lat: 'Senecio jacobaea' },
  { name_fr: 'Hoary ragwort', name_lat: 'Senecio erucifolius' },
  { name_fr: 'Marsh ragwort', name_lat: 'Senecio aquaticus' },
  { name_fr: 'Oxford ragwort', name_lat: 'Senecio squalidus' },
  { name_fr: 'Silver ragwort', name_lat: 'Senecio cineraria' },
  { name_fr: 'Rantipole', name_lat: 'Daucus carota' },
  { name_fr: 'Rapeseed', name_lat: 'Brassica napus' },
  { name_fr: 'Raspberry', name_lat: 'Rubus (Idaeobatus) spp.' },
  { name_fr: 'Black raspberry', name_lat: 'Rubus occidentalis' },
  { name_fr: 'Purple raspberry', name_lat: 'Rubus occidentalis' },
  { name_fr: 'Redbrush', name_lat: 'Cornus amomum' },
  { name_fr: 'Redbud', name_lat: 'Cercis spp.' },
  { name_fr: 'Eastern redbud', name_lat: 'Cercis canadensis' },
  { name_fr: 'Western redbud', name_lat: 'Cercis occidentalis' },
  { name_fr: 'Judas-tree', name_lat: 'Cercis siliquastrum' },
  { name_fr: 'Red ink plant', name_lat: 'Phytolacca americana' },
  { name_fr: 'Redweed', name_lat: 'Phytolacca americana' },
  { name_fr: 'Rheumatism root', name_lat: 'Apocynum cannabinum' },
  { name_fr: 'Rhubarb', name_lat: 'Rheum rhabarbarum' },
  { name_fr: 'Ribwort', name_lat: 'Plantago major' },
  { name_fr: 'Asian rice', name_lat: 'Oryza sativa' },
  { name_fr: 'African rice', name_lat: 'Oryza glaberrima' },
  { name_fr: 'Roadweed', name_lat: 'Plantago major' },
  { name_fr: 'Rocket', name_lat: '(several genera)' },
  { name_fr: "Dame's rocket", name_lat: 'Hesperis matronalis' },
  { name_fr: 'Sweet rocket', name_lat: 'Hesperis matronalis' },
  { name_fr: 'Winter rocket', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Yellow rocket', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Rocketcress', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Rose', name_lat: 'Rosa' },
  { name_fr: 'Baby rose', name_lat: 'Rosa multiflora' },
  { name_fr: 'Dwarf wild rose', name_lat: 'Rosa virginiana' },
  { name_fr: 'Low rose', name_lat: 'Rosa virginiana' },
  { name_fr: 'Multiflora rose', name_lat: 'Rosa multiflora' },
  { name_fr: 'Prairie rose', name_lat: 'Rosa virginiana' },
  { name_fr: 'Rambler rose', name_lat: 'Rosa multiflora' },
  { name_fr: 'Wild rose', name_lat: 'Rosa virginiana' },
  { name_fr: 'Rosemary', name_lat: 'Rosmarinus officinalis' },
  { name_fr: 'Rye', name_lat: 'Secale cereale' },
  { name_fr: 'Saffron crocus', name_lat: 'Crocus sativus' },
  { name_fr: 'Sanguinary', name_lat: 'Achillea millefolium' },
  { name_fr: 'Saskatoon', name_lat: 'Amelanchier alnifolia' },
  { name_fr: 'Sauce-alone', name_lat: 'Alliaria petiolata' },
  { name_fr: 'Scarlet berry', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Scoke', name_lat: 'Phytolacca americana' },
  { name_fr: 'Scotch cap', name_lat: 'Rubus occidentalis' },
  { name_fr: 'Scrambled eggs', name_lat: 'Corydalis aurea' },
  { name_fr: 'Scurvy grass', name_lat: 'Barbarea verna' },
  { name_fr: 'Serviceberry', name_lat: 'Amelanchier' },
  { name_fr: 'Common serviceberry', name_lat: 'Amelanchier arborea' },
  { name_fr: 'Downy serviceberry', name_lat: 'Amelanchier arborea' },
  { name_fr: 'Shadblow serviceberry', name_lat: 'Amelanchier canadensis' },
  { name_fr: 'Shadblow', name_lat: 'Amelanchier canadensis' },
  { name_fr: 'Shadbush', name_lat: 'Amelanchier canadensis' },
  { name_fr: 'Silkweed', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Swamp silkweed', name_lat: 'Asclepias incarnata' },
  { name_fr: 'Virginia silkweed', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Skunkweed', name_lat: 'Symplocarpus foetidus' },
  { name_fr: 'Snakeberry', name_lat: 'Solanum dulcamara' },
  { name_fr: 'Snowdrop', name_lat: 'Galanthus' },
  { name_fr: 'Sorrel', name_lat: 'Oxalis' },
  { name_fr: 'Redwood sorrel', name_lat: 'Oxalis oregana' },
  { name_fr: 'Corn speedwell', name_lat: 'Veronica arvensis' },
  { name_fr: 'Wall speedwell', name_lat: 'Veronica arvensis' },
  { name_fr: 'Spoolwood', name_lat: 'Betula papyrifera' },
  { name_fr: 'Squaw bush', name_lat: 'Cornus amomum' },
  { name_fr: 'Stammerwort', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Star-of-Persia', name_lat: 'Allium cristophii' },
  { name_fr: 'Stickweed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Strawberry', name_lat: 'Fragaria × ananassa' },
  { name_fr: 'Strawberry tree', name_lat: 'Arbutus unedo' },
  { name_fr: 'Sugarcane', name_lat: 'Saccharum' },
  { name_fr: 'Orange swallow-wort', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Silky swallow-wort', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Sneezeweed', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Sneezewort', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Sunflower', name_lat: 'Helianthus annuus' },
  { name_fr: 'Sugarplum', name_lat: 'Amelanchier canadensis' },
  { name_fr: "Soldier's woundwort", name_lat: 'Achillea millefolium' },
  { name_fr: 'Stag bush', name_lat: 'Viburnum prunifolium' },
  { name_fr: 'Orange swallow-wort', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Silky swallow-wort', name_lat: 'Asclepias syriaca' },
  { name_fr: 'Sweet potato', name_lat: 'Ipomoea batatas' },
  { name_fr: 'Sweet potato vine', name_lat: 'Ipomoea batatas' },
  { name_fr: 'Swinies', name_lat: 'Sonchus oleraceus' },
  { name_fr: 'Sycamore', name_lat: 'Platanus spp.' },
  { name_fr: 'Sycamore (California)', name_lat: 'Platanus racemosa' },
  { name_fr: 'Sycamore (Arizona)', name_lat: 'Platanus wrighitii' },
  { name_fr: 'Sycamore (American)', name_lat: 'Platanus occidentalis' },
  { name_fr: 'Common tansy', name_lat: 'Tanacetum vulgare' },
  { name_fr: 'White tansy', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Wild tansy', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Tea', name_lat: 'Camellia sinensis' },
  { name_fr: 'Appalachian tea', name_lat: 'Ilex glabra' },
  { name_fr: 'Thimbleberry', name_lat: 'Rubus occidentalis' },
  { name_fr: 'Thimbleweed', name_lat: 'Rudbeckia laciniata' },
  { name_fr: 'Thousand-leaf', name_lat: 'Achillea millefolium' },
  { name_fr: 'Thousand-seal', name_lat: 'Achillea millefolium' },
  { name_fr: 'Tassel weed', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Thistle', name_lat: '(Several genera)' },
  { name_fr: 'Annual sow thistle', name_lat: 'Sonchus oleraceus' },
  { name_fr: 'California thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Canada thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Corn thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Corn sow thistle', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Creeping thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Cursed thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Field sow thistle', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Green thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Hard thistle', name_lat: 'Cirsium arvense' },
  { name_fr: "Hare's thistle", name_lat: 'Sonchus oleraceus' },
  { name_fr: 'Milk thistle', name_lat: 'Sonchus oleraceus' },
  { name_fr: 'Nodding thistle', name_lat: 'Carduus nutans L.' },
  { name_fr: 'Perennial thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Prickly thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Sharp-fringed sow Thistle', name_lat: 'Sonchus asper' },
  { name_fr: 'Small-flowered Thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Spiny sow thistle', name_lat: 'Sonchus asper' },
  { name_fr: 'Spiny-leaved sow Thistle', name_lat: 'Sonchus asper' },
  { name_fr: 'Swine thistle', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Tree sow thistle', name_lat: 'Sonchus arvensis' },
  { name_fr: 'Way thistle', name_lat: 'Cirsium arvense' },
  { name_fr: 'Thyme', name_lat: 'Thymus vulgaris' },
  { name_fr: 'Tickleweed', name_lat: 'Veratrum viride' },
  { name_fr: 'Tobacco plant', name_lat: 'Nicotiana' },
  { name_fr: 'Tomato', name_lat: 'Solanum lycopersicum' },
  { name_fr: 'Toothwort', name_lat: 'Cardamine concatenata' },
  { name_fr: 'Cutleaf toothwort', name_lat: 'Cardamine concatenata' },
  { name_fr: 'Purple-flowered Toothwort', name_lat: 'Cardamine concatenata' },
  { name_fr: 'Touch-me-not', name_lat: 'Impatiens capensis' },
  { name_fr: "Traveller's joy", name_lat: 'Clematis virginiana' },
  { name_fr: 'Tread-softly', name_lat: 'Solanum carolinense' },
  { name_fr: 'Tree tobacco', name_lat: 'Nicotiana glauca' },
  { name_fr: 'Trillium', name_lat: 'Trillium spp.' },
  { name_fr: 'Western trillium', name_lat: 'Trillium ovatum' },
  { name_fr: 'Western wake robin', name_lat: 'Trillium ovatum' },
  { name_fr: 'White trillium', name_lat: 'Trillium grandiflorum' },
  { name_fr: 'Tuber-root', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Tulip', name_lat: 'Tulipa' },
  { name_fr: 'Tulsi', name_lat: 'Ocimum santalum' },
  { name_fr: 'Umbrella palm', name_lat: 'Hedyscepe canterburyana' },
  { name_fr: 'Umbrella papyrus', name_lat: 'Cyperus alternifolius' },
  { name_fr: 'Vanilla orchid', name_lat: 'Vanilla' },
  { name_fr: 'Varnish tree', name_lat: 'Koelreuteria paniculata' },
  { name_fr: 'Velvet bean', name_lat: 'Mucuna pruriens' },
  { name_fr: 'Viburnum', name_lat: 'Viburnum' },
  { name_fr: 'Blackhaw viburnum', name_lat: 'Viburnum prunifolium' },
  { name_fr: 'Leatherleaf viburnum', name_lat: 'Viburnum rhytidophyllum' },
  { name_fr: 'African violet', name_lat: 'Saintpaulia species' },
  { name_fr: 'Damask violet', name_lat: 'Hesperis matronalis' },
  { name_fr: "Dame's violet", name_lat: 'Hesperis matronalis' },
  { name_fr: "Dog's-tooth-violet", name_lat: 'Erythronium dens-canis' },
  { name_fr: 'Violet bloom', name_lat: 'Solanum dulcamara' },
  { name_fr: "Viper's grass", name_lat: 'Scorzonera hispanica' },
  { name_fr: "Virgin's bower", name_lat: 'Clematis virginiana' },
  { name_fr: "Virginia virgin's bower", name_lat: 'Clematis virginiana' },
  { name_fr: 'Voodoo lily', name_lat: 'Dracunculus vulgaris' },
  { name_fr: 'Walnut (California walnut)', name_lat: 'Juglans californica' },
  { name_fr: 'Walnut', name_lat: 'Juglans sp.' },
  { name_fr: 'Waybread', name_lat: 'Plantago major' },
  { name_fr: 'Western redbud', name_lat: 'Cercis occidentalis' },
  { name_fr: 'Wheat', name_lat: 'Triticum spp.' },
  { name_fr: "White man's foot", name_lat: 'Plantago major' },
  { name_fr: 'White-root', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Wild cotton', name_lat: 'Apocynum cannabinum' },
  { name_fr: 'Wild hops', name_lat: 'Clematis virginiana' },
  { name_fr: 'Willow', name_lat: 'Salix' },
  { name_fr: 'Coyote willow', name_lat: 'Salix exigua' },
  { name_fr: 'Goodding willow', name_lat: 'Salix gooddingii' },
  { name_fr: 'Red willow', name_lat: 'Cornus amomum' },
  { name_fr: 'Rose willow', name_lat: 'Cornus amomum' },
  { name_fr: 'Windroot', name_lat: 'Asclepias tuberosa' },
  { name_fr: 'Wineberry', name_lat: 'Rubus phoenicolasius' },
  { name_fr: 'Winterberry', name_lat: 'Ilex verticillata' },
  { name_fr: 'American winterberry', name_lat: 'Ilex verticillata' },
  { name_fr: 'Evergreen winterberry', name_lat: 'Ilex glabra' },
  { name_fr: 'Virginia winterberry', name_lat: 'Ilex verticillata' },
  { name_fr: 'Wintercress', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Early wintercress', name_lat: 'Barbarea verna' },
  { name_fr: 'Woodbine', name_lat: 'Clematis virginiana' },
  { name_fr: 'Woolly morning glory', name_lat: 'Argyreia nervosa' },
  { name_fr: 'Roman wormwood', name_lat: 'Ambrosia artemisiifolia' },
  { name_fr: 'Wound rocket', name_lat: 'Barbarea vulgaris' },
  { name_fr: 'Yarrow', name_lat: 'Achillea' },
  { name_fr: 'Common yarrow', name_lat: 'Achillea millefolium' },
  { name_fr: 'Fernleaf yarrow', name_lat: 'Achillea filipendulina' },
  { name_fr: 'Sneezewort yarrow', name_lat: 'Achillea ptarmica' },
  { name_fr: 'Woolly yarrow', name_lat: 'Achillea tomentosa' },
  { name_fr: 'Yellow fieldcress', name_lat: 'Rorippa sylvestris' },
  { name_fr: 'Yellowwood', name_lat: 'Cladrastis lutea' },
  { name_fr: 'Yellow coneflower', name_lat: 'Echinacea paradoxa' },
  { name_fr: 'Yam', name_lat: 'Ipomoea batatas' },
  { name_fr: 'Yunnan camellia', name_lat: 'Camellia yunnanensis' },
  { name_fr: 'Zebrawood', name_lat: 'Brachystegia spiciformis' },
  { name_fr: 'Zedoary', name_lat: 'Curcuma zedoaria' },
].map((x, i) => ({ ...x, id: `vegetal-${i + 1}` }))
