import type { Vegetal } from 'type'

export const vegetals: Vegetal[] = [
  { name_fr: 'Alder', name_la: 'Alnus', wet: false },
  { name_fr: 'Black alder', name_la: 'Alnus glutinosa', wet: true },
  { name_fr: 'Common alder', name_la: 'Alnus glutinosa', wet: false },
  { name_fr: 'False alder', name_la: 'Ilex verticillata', wet: false },
  { name_fr: 'Gray alder', name_la: 'Alnus incana', wet: true },
  { name_fr: 'Speckled alder', name_la: 'Alnus incana', wet: true },
  { name_fr: 'Striped alder', name_la: 'Ilex verticillata', wet: true },
  { name_fr: 'White alder', name_la: 'Alnus incana', wet: false },
  { name_fr: 'Almond', name_la: 'Prunus amygdalus', wet: true },
  { name_fr: 'Tall ambrosia', name_la: 'Ambrosia trifida', wet: false },
  { name_fr: 'Durian kura kura', name_la: 'Durio testudinarum', wet: true },
  { name_fr: 'Durian munjit', name_la: 'Durio grandiflorus', wet: true },
  { name_fr: 'Durian pulu', name_la: 'Durio kutejensis', wet: false },
  { name_fr: 'Red durian', name_la: 'Durio dulcis', wet: false },
  { name_fr: 'Dye-leaves', name_la: 'Ilex glabra', wet: false },
  { name_fr: 'Easter orchid', name_la: 'Cattleya schroederae', wet: false },
  { name_fr: 'Earth gall', name_la: 'Veratrum viride', wet: false },
  { name_fr: 'Elderberry', name_la: 'Sambucus', wet: false },
  { name_fr: 'Elegant lupine', name_la: 'Lupinus elegans', wet: false },
  { name_fr: 'Elephant apple', name_la: 'Dillenia indica', wet: true },
  { name_fr: "English bull's eye", name_la: 'Rudbeckia hirta', wet: false },
  { name_fr: 'Eucalyptus', name_la: 'Eucalyptus spp.', wet: false },
  { name_fr: 'Evergreen huckleberry', name_la: 'Vaccinium ovatum', wet: false },
  { name_fr: 'Extinguisher moss', name_la: 'Encalypta', wet: true },
  { name_fr: 'Eytelia', name_la: 'Amphipappus', wet: true },
  { name_fr: 'Fair-maid-of-France', name_la: 'Achillea ptarmica', wet: true },
  { name_fr: 'Fellenwort', name_la: 'Solanum dulcamara', wet: true },
  { name_fr: 'Felonwood', name_la: 'Solanum dulcamara', wet: false },
  { name_fr: 'Felonwort', name_la: 'Solanum dulcamara', wet: false },
  { name_fr: 'Fennel', name_la: 'Foeniculum vulgare', wet: false },
  {
    name_fr: 'Boston fern or sword fern',
    name_la: 'Nephrolepis exaltata',
    wet: false,
  },
  {
    name_fr: 'Christmas fern',
    name_la: 'Polystichum acrostichoides',
    wet: false,
  },
  { name_fr: 'Coast polypody', name_la: 'Polypodium scouleri', wet: false },
  {
    name_fr: 'Kimberly queen fern',
    name_la: 'Nephrolepis obliterata',
    wet: false,
  },
  { name_fr: 'Common onion', name_la: 'Allium cepa', wet: false },
  { name_fr: 'Giant onion', name_la: 'Allium giganteum', wet: false },
  { name_fr: 'Nodding onion', name_la: 'Allium cernuum', wet: true },
  { name_fr: 'Tree onion', name_la: 'Allium canadense', wet: false },
  { name_fr: 'Wild onion', name_la: 'Allium canadense', wet: true },
  { name_fr: 'Osage orange', name_la: 'Maclura pomifera', wet: false },
  { name_fr: 'sweet orange', name_la: 'Citrus × sinensis', wet: false },
  { name_fr: 'Wild orange', name_la: 'Maclura pomifera', wet: true },
  { name_fr: 'Orange-root', name_la: 'Asclepias tuberosa', wet: true },
  { name_fr: 'Osage', name_la: 'Maclura pomifera', wet: false },
  { name_fr: 'Osier', name_la: 'Salix', wet: false },
  { name_fr: 'Pokeweed', name_la: 'Phytolacca americana', wet: false },
  { name_fr: 'Polkweed', name_la: 'Symplocarpus foetidus', wet: false },
  { name_fr: 'Polecat weed', name_la: 'Symplocarpus foetidus', wet: false },
  { name_fr: 'Oxford ragwort', name_la: 'Senecio squalidus', wet: true },
  { name_fr: 'Silver ragwort', name_la: 'Senecio cineraria', wet: true },
  { name_fr: 'Rantipole', name_la: 'Daucus carota', wet: true },
  { name_fr: 'Rapeseed', name_la: 'Brassica napus', wet: true },
  { name_fr: 'Raspberry', name_la: 'Rubus (Idaeobatus) spp.', wet: false },
  { name_fr: 'Black raspberry', name_la: 'Rubus occidentalis', wet: false },
  { name_fr: 'Purple raspberry', name_la: 'Rubus occidentalis', wet: false },
  { name_fr: 'Redbrush', name_la: 'Cornus amomum', wet: false },
  { name_fr: 'Redbud', name_la: 'Cercis spp.', wet: false },
  { name_fr: 'Eastern redbud', name_la: 'Cercis canadensis', wet: false },
  { name_fr: 'Western redbud', name_la: 'Cercis occidentalis', wet: false },
  { name_fr: 'Judas-tree', name_la: 'Cercis siliquastrum', wet: false },
  { name_fr: 'Red ink plant', name_la: 'Phytolacca americana', wet: false },
  { name_fr: 'Redweed', name_la: 'Phytolacca americana', wet: false },
  { name_fr: 'Rheumatism root', name_la: 'Apocynum cannabinum', wet: false },
  { name_fr: 'Rhubarb', name_la: 'Rheum rhabarbarum', wet: true },
  { name_fr: 'Ribwort', name_la: 'Plantago major', wet: false },
  { name_fr: 'Asian rice', name_la: 'Oryza sativa', wet: false },
  { name_fr: 'African rice', name_la: 'Oryza glaberrima', wet: false },
  { name_fr: 'Roadweed', name_la: 'Plantago major', wet: false },
  { name_fr: 'Rocket', name_la: '(several genera)', wet: false },
  { name_fr: "Dame's rocket", name_la: 'Hesperis matronalis', wet: false },
  { name_fr: 'Sweet rocket', name_la: 'Hesperis matronalis', wet: false },
  { name_fr: 'Winter rocket', name_la: 'Barbarea vulgaris', wet: false },
  { name_fr: 'Yellow rocket', name_la: 'Barbarea vulgaris', wet: true },
  { name_fr: 'Rocketcress', name_la: 'Barbarea vulgaris', wet: true },
  { name_fr: 'Rose', name_la: 'Rosa', wet: true },
  { name_fr: 'Baby rose', name_la: 'Rosa multiflora', wet: false },
  { name_fr: 'Dwarf wild rose', name_la: 'Rosa virginiana', wet: false },
  { name_fr: 'Yellow fieldcress', name_la: 'Rorippa sylvestris', wet: false },
  { name_fr: 'Yellowwood', name_la: 'Cladrastis lutea', wet: false },
  { name_fr: 'Yellow coneflower', name_la: 'Echinacea paradoxa', wet: false },
  { name_fr: 'Yam', name_la: 'Ipomoea batatas', wet: false },
  { name_fr: 'Yunnan camellia', name_la: 'Camellia yunnanensis', wet: true },
  { name_fr: 'Zebrawood', name_la: 'Brachystegia spiciformis', wet: true },
  { name_fr: 'Zedoary', name_la: 'Curcuma zedoaria', wet: true },
].map((x, i) => ({
  ...x,
  id: `vegetal-${i + 1}`,
}))
